[WIP] Initial work on contributing guidelines for specifications
ipld/specs pull request #122
Opened 2019-05-13 13:20 UTC by mikeal

2019-05-28 03:32 UTC, rvagg requested changes

2019-05-28 03:32 UTC, rvagg commented on CONTRIBUTING.md
> +
I suggest we also say how to identify the stage of a spec, something like:

> Specification documents should include a descriptor in their heading that indicates their status in the staging process. e.g. "Prescriptive - Draft", or "Descriptive - Final".

Then we can go about amending what's in here.

2019-05-28 03:46 UTC, rvagg commented
#123 introduces non-spec-but-related content, the README contains non-spec-but-related material, https://github.com/ipld/specs/blob/master/data-structures/multiblock-collections.md isn't strictly a "spec". We need to be more clear about what a "spec" is and how to identify one. Do we use directories to make it work? Do we identify them clearly in their title and/or filenames? How do the merge rules apply to things that aren't strictly specs?

2019-05-29 19:45 UTC, mikeal commented
If there are no objections I’ll merge this tomorrow.

2019-06-05 20:48 UTC, mikeal commented
What should we do with this now? Was it all merged as part of the other PR or are there parts of it that weren’t included?

2019-06-05 23:21 UTC, rvagg commented
yes, all included along with some extra words, including notes about non-spec material (like "concepts" and README)

2019-06-05 23:21 UTC, closed without merging