doc: add glossary with entry w/ DAG
ipld/specs pull request #167
Opened 2019-08-14 23:10 UTC by mikeal

fixes #77

2019-08-19 10:01 UTC, vmx requested changes

2019-08-19 10:01 UTC, vmx commented on README.md
> +It a tree where two branches can point to the same sub-branch, but only in one direction
"It **is** a tree"

2019-08-20 00:57 UTC, rvagg approved these changes

2019-10-01 12:45 UTC, vmx approved these changes

2019-10-01 12:46 UTC, vmx commented
It was approved by @rvagg, I just force-pushed a new version with the typo I mentioned fixed. Hence merging it.

2019-10-01 12:46 UTC, merged